services:
  - type: web
    name: susibert
    env: node
    buildCommand: ./build-render.sh
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_CODE
        sync: false
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"