services:
  - type: web
    name: susibert
    env: node
    buildCommand: chmod +x ./ultra-build.sh && ./ultra-build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_CODE
        sync: false
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"